Repository GrayYang02/fridge, pull requests merged in 2025-03, with the labels that each got.

#7 Refactor Navigation & Routing Across Multiple Components
  backend/demo/log/__init__.py
  fridgeui/src/App.js
  fridgeui/src/components/Fridge/Fridge.jsx
  fridgeui/src/components/Navbar.jsx
  fridgeui/src/components/Profile/Profile.jsx
  fridgeui/src/components/Recipe/Recipe.jsx
  fridgeui/src/components/SignupLogin/Login.js
Labels: documentation

#11 Show recipe detail with GET port WITHOUT [AUTH]
  backend/core/api_chat.py
  backend/core/models.py
  backend/core/temp_recipe_detail.py
  backend/core/urls.py
  backend/demo/log/__init__.py
  fridgeui/src/App.js
  fridgeui/src/api.js
  fridgeui/src/components/RecipeDetail/RecipeDetail.jsx
  fridgeui/src/components/RecipeGenerate/RecipeGen.jsx
  fridgeui/src/components/RecipeGenerate/assets/applepic.png
  fridgeui/src/components/RecipeGenerate/assets/potpic.png
  fridgeui/src/components/RecipeGenerate/assets/profilepic.png
Labels: enhancement

#13 TOKEN BUG FIXED
  fridgeui/src/components/ProtectedRoute.jsx
  fridgeui/src/components/SignupLogin/Login.js
Labels: bug

#14 Fix and Improve Unit Tests for Login and Signup Components
  fridgeui/package-lock.json
  fridgeui/package.json
  fridgeui/src/App.test.js
  fridgeui/src/components/SignupLogin/Login.js
  fridgeui/src/components/SignupLogin/SignUp.js
  fridgeui/src/components/SignupLogin/__tests__/Login.test.js
  fridgeui/src/components/SignupLogin/__tests__/SignUp.test.js
Labels: enhancement
